#!/bin/sh
sudo ifconfig eth0 84.240.3.129
#set time
sudo date -s "18 Oct 2011 19:38"
#start server
./ngircd -f ./ngircd.conf
#join for channel creation time
printf "Start up client for channel creation time\n"
sleep 40
printf "Prepare\n"
sleep 5
printf "Join now for channel creation time\n"
sleep 10
#date for topic
sudo date -s "2 Oct 2014 15:28"
#join for setting topic
cat set_topic.script| ./replay_skript | nc irc.freenode.net 6667
sudo date -s "13 Oct 2014 11:26"

